name: swipe
description: "Swipe Cleaner - Organize suas fotos e v√≠deos"
publish_to: "none"
version: 0.0.26+26

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_manager: ^3.6.0
  video_player: ^2.9.2
  flutter_card_swiper: ^7.0.1
  intl: ^0.19.0
  sqflite: ^2.4.1
  path: ^1.9.0
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  image: ^4.7.2
  flutter_local_notifications: ^20.0.0
  shared_preferences: ^2.5.4
  timezone: ^0.10.1
  flutter_timezone: ^3.0.1
  sensors_plus: ^7.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/swipe_right_rounded 16.png"
  adaptive_icon_background: "#6C5CE7"
  adaptive_icon_foreground: "assets/logo_icon_padded.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
